### ISSUE TITLE
Xin dataset

### ISSUE THREAD

**Issue by vuthithao** [huyhoang17/Vietnamese_Handwriting_Recognition#1]
Anh có thể cho em xin dataset được không ạ??? Em mới tìm hiểu OCR. Em cảm ơn

**Comment by huyhoang17** [comment]
@vuthithao Chào bạn, bạn gửi mail của bạn cho mình nhé!

**Comment by vuthithao** [comment]
vuthithao04081996@gmail.com ạ
Em cảm ơn anh  :D

Vào 06-12-2018 00:16, "Phan Hoang" <notifications@github.com> đã viết:

@vuthithao <https://github.com/vuthithao> Chào bạn, bạn gửi mail của bạn
cho mình nhé!

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/huyhoang17/Vietnamese_Handwriting_Recognition/issues/1#issuecomment-444566916>,
or mute the thread

**Comment by Truong-Thanh-Quang** [comment]
Cho mình xin dataset với. Cảm ơn @huyhoang17.
Email của mình: truongthanhquang@gmail.com.

**Comment by huyhoang17** [comment]
@Truong-Thanh-Quang mình có cập nhật link dataset trong README.md rồi đó bạn https://github.com/huyhoang17/Vietnamese_Handwriting_Recognition
