### ISSUE TITLE
Can you also please share the sample dataset used for this trainin?

### ISSUE THREAD

**Issue by GireeshS22** [huyhoang17/Vietnamese_Handwriting_Recognition#2]
Hi Huyhoang & team,

Can you please share few sample datasets used for this training?

Thanks!

**Comment by huyhoang17** [comment]
thanks @GireeshS22 for your interest, sr for my late reply. You can download training data from this link: https://www.dropbox.com/s/zk82qkidkqma8bj/vn_handwriting_data.zip?dl=0 . I also update this one in README.md

**Comment by GireeshS22** [comment]
Thanks for the data.
